name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build the executable with PyInstaller
      - name: Build executable
        run: |
          pyinstaller --onefile main.py
        shell: cmd

      # Step 5: Upload artifact
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe-build
          path: dist/*.exe
